### ISSUE TITLE
FATAL EXCEPTION: DefaultDispatcher-worker-3

### ISSUE THREAD

**Issue by YiBeomSeok** [capstone-design-team4/Client#1]
현재 코루틴 동기화 방식으로 retrofit2 사용시
main 액티비티에서 fragment 전환 시
팅기는 현상이 발생.
비슷한 exception 사례를 가져옴

@Transaction
    suspend fun getRandomRN(num: Int):List<Question>{
     val result = getRandomWrongOrNotAnsweredQuestionsByCount(num)
        val last = getLastQuizNumber()

        val newResult = mutableListOf<Question>()

        result?.forEachIndexed{ index,element ->
            element.status=0
            element.quiz_number = last+1
            newResult[index] = element  // this is line 91
        }

        result?.let { updateQuestions(newResult) }
        return newResult
    }

error

com.example.android.myapplication E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-2
    Process: com.example.android.myapplication, PID: 25245
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.set(ArrayList.java:453)
        at com.example.android.webpooyeshelevatorquize.data.QuestionDao$DefaultImpls.getRandomRN(QuestionDao.kt:91)

해결
The newResult list is empty, you cannot use newResult[index] = element to add new elements to it. Use newResult += element or newResult.add(emenent) instead.

**Comment by YiBeomSeok** [comment]
현재

GraphFragment 중
 
        val call2 = api.getPredictionGen()
        val execute2 = call2.execute()
        val body2 = execute2.body()
        Log.d("log", "getPredictionGen1 :" + execute2.toString())
        Log.d("log", "getPredictionGen2 :" + body2.toString())
        Log.d(
            "log", "getPredictionGen3 :" + body2?.count().toString()
        )

부분이 문제가 있는 상황
다음과 같은 문제가 추가 발생
Process: com.capstone.jeonshimclient, PID: 8649
java.io.EOFException: \n not found: limit=1 content=0d…

**Comment by YiBeomSeok** [comment]
val body = execute.body()
        Log.d("log", "getMeasurementGenWeek1 :" + execute.toString())
        Log.d("log", "getMeasurementGenWeek2 :" + body.toString())
        Log.d(
            "log", "getMeasurementGenWeek3 :" + body?.count().toString()
        )
        if (body.toString() != "[]" && body != null) {
            val count = body?.count()!!
            for (index in 0 until count) {
                val targetTime =
                    LocalDateTime.parse(body[index].timeCurrent).dayOfWeek
                if (targetTime < STARTDAYOFWEEK || targetTime > ENDDAYOFWEEK)
                    continue

                val current = body[index].current
                val voltage = body[index].voltage

                if (!genTimeHash.containsKey(targetTime))
                    genTimeHash[targetTime] = 15 * current * voltage
                else
                    genTimeHash[targetTime] =
                        15 * current * voltage + genTimeHash.getValue(targetTime)
            }
        }

기존 코드에서
try catch로 예외를 catch해주어야 했는데 이 부분이 빠져
예외 상황이 발생했을 때 exception error로 튕겼던 것

다음과 같이 변환해주면 됨.

        try {
            val execute = call.execute()
            val body = execute.body()
            Log.d("log", "getMeasurementGenWeek1 :" + execute.toString())
            Log.d("log", "getMeasurementGenWeek2 :" + body.toString())
            Log.d(
                "log", "getMeasurementGenWeek3 :" + body?.count().toString()
            )
            if (body.toString() != "[]" && body != null) {
                val count = body?.count()!!
                for (index in 0 until count) {
                    val targetTime =
                        LocalDateTime.parse(body[index].timeCurrent).dayOfWeek
                    if (targetTime < STARTDAYOFWEEK || targetTime > ENDDAYOFWEEK)
                        continue

                    val current = body[index].current
                    val voltage = body[index].voltage

                    if (!genTimeHash.containsKey(targetTime))
                        genTimeHash[targetTime] = 15 * current * voltage
                    else
                        genTimeHash[targetTime] =
                            15 * current * voltage + genTimeHash.getValue(targetTime)
                }
            }
        } catch (e: Exception) {
            generator_present_expected_Graph_API()
        }

**Comment by YiBeomSeok** [comment]
### 2022-05-30 현재 또 다시 비슷한 증상이 발현
main activity에서 바텀네비게이션을 통해 fragment replace 중에 생기는 것으로 판단함.

16405-16435/com.capstone.jeonshimclient E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.capstone.jeonshimclient, PID: 16405
    java.lang.IllegalStateException: Fragment GraphFragment{4171c09} (175bc419-4622-4cec-be96-4f114917e9ed) not attached to a context.
        at androidx.fragment.app.Fragment.requireContext(Fragment.java:900)
        at com.capstone.jeonshimclient.GraphFragment$onCreate$1$1.invokeSuspend(GraphFragment.kt:80)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

        bnv_main.run {
            setOnItemSelectedListener {
                when (it.itemId) {
                    R.id.first -> {
                        // 다른 프래그먼트 화면으로 이동하는 기능
                        if (nowFragmentNumber != 1) {
                            nowFragmentNumber = 1
                            val reductionStatusFragment = ReductionStatusFragment()
                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, reductionStatusFragment).commit()
                        }
                    }
                    R.id.second -> {
                        if (nowFragmentNumber != 2) {
                            nowFragmentNumber = 2
                            val graphFragment = GraphFragment()
                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, graphFragment).commit()
                        }
                    }
                    R.id.third -> {
                        if (nowFragmentNumber != 3) {
                            nowFragmentNumber = 3
                            val userFragment = UserFragment()
                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, userFragment).commit()
                        }
                    }
                }
                true
            }
            selectedItemId = R.id.first
        }

**val reductionStatusFragment = ReductionStatusFragment()**
와 같이 fragment 인스턴스 생성을 버튼 클릭시마다 해주어서 생긴 문제.
천천히 변경할 때는 문제가 없지만,
빠르게 변경시에는 fragment 인스턴스 생성이 미처 끝나기 전에 다시 동일한 이름의 새로운 인스턴스 생성을 하게 되어
충돌이 있었던 것 같음
fragment 생성은 onCreate 시에 생성되도록 선언해 주고 버튼에서는 사용만 하도록 수정

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
        var api: APIS = APIS.create()
        val reductionStatusFragment = ReductionStatusFragment()
        val graphFragment = GraphFragment()
        val userFragment = UserFragment()

        // 하단 탭이 눌렸을 때 화면을 전환하기 위해선 이벤트 처리하기 위해 BottomNavigationView 객체 생성
        var bnv_main = findViewById<BottomNavigationView>(R.id.bnv_main)

        // OnNavigationItemSelectedListener를 통해 탭 아이템 선택 시 이벤트를 처리
        // navi_menu.xml 에서 설정했던 각 아이템들의 id를 통해 알맞은 프래그먼트로 변경하게 한다.
        bnv_main.run {
            setOnItemSelectedListener {
                when (it.itemId) {
                    R.id.first -> {
                        // 다른 프래그먼트 화면으로 이동하는 기능
                        if (nowFragmentNumber != 1) {
                            nowFragmentNumber = 1

                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, reductionStatusFragment).commit()
                        }
                    }
                    R.id.second -> {
                        if (nowFragmentNumber != 2) {
                            nowFragmentNumber = 2

                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, graphFragment).commit()
                        }
                    }
                    R.id.third -> {
                        if (nowFragmentNumber != 3) {
                            nowFragmentNumber = 3
                            supportFragmentManager.beginTransaction()
                                .replace(R.id.fl_container, userFragment).commit()
                        }
                    }
                }
                true
            }
            selectedItemId = R.id.first
        }

    }

사소해 보이지만 굉장히 조심해야할 부분
Logcat을 보더라도 Exception 위치가 MainActivty가 아닌 Fragment에서 나타나기 때문에
지켜주지 않으면 원인을 찾기 매우 힘들 수 있다
